import Head from 'next/head';
import style from '../styles/main.module.scss';
import axios from 'axios';
import { useState } from 'react';
import apiKey from '../../apiKey.json';

export default function Home() {
  const [book, setBook] = useState("");
  const [result, setResult] = useState([]);
  const key = apiKey[0].apiKey;


  function newBook(e: any) {
    setBook(e.target.value);
  }

  function search(e) {
    e.preventDefault();
    axios.get(`https://www.googleapis.com/books/v1/volumes?q=${book}&key=${key}&maxResults=40`)
      .then(info => {
        console.log(info.data.items);
        setResult(info.data.items);
      });
    console.log(book);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <input onChange={newBook} type="text" placeholder="digite um livro" />
        <button onClick={search}>Pesquisar</button>

        {result != [] ?
          (result.map((item, key) =>
            <>
              {item.volumeInfo.title && item.volumeInfo.imageLinks ?
                <>
                  <p key={key}>{item.volumeInfo.title}</p>
                  <img src={item.volumeInfo.imageLinks.thumbnail} alt="" />
                </> :
                <>
                  <p key={key}>{item.volumeInfo.title}</p>
                  <p>não tem</p>
                </>

              }
            </>
          )) : (<></>)
        }

      </main>
    </>
  )
}