import Head from 'next/head';
import style from '../styles/main.module.scss';
import { Search } from '../components/Search';
import { ResultSearch } from '../components/ResultSearch';
import {Footer} from '../components/Footer';
import { useBooks } from '../contexts/BooksContext';

export default function Home() {
  const { myResult } = useBooks();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.main}>

        <Search />

        {myResult.length === 0 ?
          (
            <div className={style.imgContainer}>
              <img src="/img-fundo.png" alt="" />
            </div>
          ) : (
            <ResultSearch />
          )
        }
      </main>
    </>
  )
}